# Dockerfile

FROM python:3.11-slim

WORKDIR /app
ENV PYTHONPATH=/app
ENV PYTHONUNBUFFERED=1

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# This CMD will be overridden by docker-compose service commands
CMD ["python", "main.py"]
