
services:
  app:
    build: .
    container_name: trading-app
    restart: unless-stopped
    env_file: .env
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: trading-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./storage/sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  pgdata:
